---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-cnpg-cluster
  namespace: immich
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.7
  storage:
    storageClass: freenas-iscsi-csi
    size: 10Gi
  bootstrap:
    initdb:
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
  postgresql:
    shared_preload_libraries: # load pgvecto.rs shared library
    - "vectors.so"

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: immich-cnpg-metrics
  namespace: immich
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: immich-cnpg-cluster
  podMetricsEndpoints:
    - port: metrics

