---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-cnpg-cluster
  namespace: immich
spec:
  instances: 1

  storage:
    storageClass: freenas-iscsi-csi
    size: 10Gi

  #imageName: ghcr.io/immich-app/postgres:18-vectorchord0.5.3-pgvector0.8.1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.1-1.0.0

  postgresql:
    shared_preload_libraries:
    - "vchord.so"

  bootstrap:
    initdb:
      postInitApplicationSQL:
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: immich-cnpg-metrics
  namespace: immich
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: immich-cnpg-cluster
  podMetricsEndpoints:
    - port: metrics

