---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-cnpg-cluster
  namespace: immich
spec:
  instances: 1
  storage:
    storageClass: freenas-iscsi-csi
    size: 10Gi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: immich-cnpg-metrics
  namespace: immich
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: immich-cnpg-cluster
  podMetricsEndpoints:
    - port: metrics

