---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: immich
    namespace: flux-system
  values:
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-library
    server:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                # renovate: datasource=github-releases depName=immich-app/immich
                tag: "v2.5.2"
              resources:
                requests:
                  cpu: 100m
                  memory: 2048M
              env:
                # Database connection
                DB_HOSTNAME: immich-cnpg-cluster-rw.immich.svc.cluster.local
                DB_DATABASE_NAME:
                  valueFrom:
                    secretKeyRef:
                      name: immich-cnpg-cluster-app
                      key: dbname
                DB_PORT:
                  valueFrom:
                    secretKeyRef:
                      name: immich-cnpg-cluster-app
                      key: port
                DB_USERNAME:
                  valueFrom:
                    secretKeyRef:
                      name: immich-cnpg-cluster-app
                      key: username
                DB_PASSWORD:
                  valueFrom:
                    secretKeyRef:
                      name: immich-cnpg-cluster-app
                      key: password
      ingress:
        main:
          enabled: true
          className: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-production"
            external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
            external-dns/is-public: "true"
            hajimari.io/enable: "true"
            hajimari.io/icon: "mdi:camera-iris"
            # proxy-body-size is set to 0 to remove the body limit on file uploads
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            # timeouts (avoid ingress closing the connection mid-upload / long processing)
            nginx.ingress.kubernetes.io/proxy-connect-timeout: "75"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
            # avoid request-body buffering to disk (reduces “mysterious” disconnects when temp storage is constrained)
            nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
          hosts:
          - host: "immich.${SECRET_DOMAIN}"
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - "immich.${SECRET_DOMAIN}"
            secretName: immich-tls
    machine-learning:
      persistence:
        cache:
          existingClaim: immich-ml

    valkey:
      enabled: true
