apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"node-linux","app.kubernetes.io/csi-role":"node","app.kubernetes.io/instance":"zfs-iscsi","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"democratic-csi","helm.sh/chart":"democratic-csi-0.13.7"},"name":"zfs-iscsi-democratic-csi-node","namespace":"democratic-csi"},"spec":{"selector":{"matchLabels":{"app.kubernetes.io/component":"node-linux","app.kubernetes.io/csi-role":"node","app.kubernetes.io/instance":"zfs-iscsi","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"democratic-csi"}},"template":{"metadata":{"annotations":{"checksum/configmap":"6aec39faec18176138f529a4ae68702ec821b436b11e320a799f22eeb85ddc54","checksum/secret":"be8a704348953ac7de0579f3cd7d70d610a56e26228303d217a2f240d7f79916"},"labels":{"app.kubernetes.io/component":"node-linux","app.kubernetes.io/csi-role":"node","app.kubernetes.io/instance":"zfs-iscsi","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"democratic-csi"}},"spec":{"containers":[{"args":["--csi-version=1.5.0","--csi-name=org.democratic-csi.iscsi","--driver-config-file=/config/driver-config-file.yaml","--log-level=info","--csi-mode=node","--server-socket=/csi-data/csi.sock.internal"],"env":[{"name":"CSI_NODE_ID","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"spec.nodeName"}}},{"name":"NODE_EXTRA_CA_CERTS","value":"/tmp/certs/extra-ca-certs.crt"}],"image":"docker.io/democraticcsi/democratic-csi:latest","livenessProbe":{"exec":{"command":["bin/liveness-probe","--csi-version=1.5.0","--csi-address=/csi-data/csi.sock.internal"]},"failureThreshold":3,"initialDelaySeconds":10,"periodSeconds":60,"timeoutSeconds":15},"name":"csi-driver","securityContext":{"allowPrivilegeEscalation":true,"capabilities":{"add":["SYS_ADMIN"]},"privileged":true},"terminationMessagePath":"/tmp/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/csi-data","name":"socket-dir"},{"mountPath":"/var/lib/kubelet","mountPropagation":"Bidirectional","name":"kubelet-dir"},{"mountPath":"/etc/iscsi","mountPropagation":"Bidirectional","name":"iscsi-dir"},{"mountPath":"/var/lib/iscsi","mountPropagation":"Bidirectional","name":"iscsi-info"},{"mountPath":"/lib/modules","name":"modules-dir","readOnly":true},{"mountPath":"/etc/localtime","name":"localtime","readOnly":true},{"mountPath":"/run/udev","name":"udev-data"},{"mountPath":"/host","mountPropagation":"Bidirectional","name":"host-dir"},{"mountPath":"/sys","name":"sys-dir"},{"mountPath":"/dev","name":"dev-dir"},{"mountPath":"/config","name":"config"},{"mountPath":"/tmp/certs","name":"extra-ca-certs"}]},{"env":[{"name":"BIND_TO","value":"unix:///csi-data/csi.sock"},{"name":"PROXY_TO","value":"unix:///csi-data/csi.sock.internal"}],"image":"docker.io/democraticcsi/csi-grpc-proxy:v0.5.3","name":"csi-proxy","volumeMounts":[{"mountPath":"/csi-data","name":"socket-dir"}]},{"args":["--v=5","--csi-address=/csi-data/csi.sock","--kubelet-registration-path=/var/lib/kubelet/plugins/org.democratic-csi.iscsi/csi.sock"],"env":[{"name":"KUBE_NODE_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"spec.nodeName"}}}],"image":"registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1","livenessProbe":{"exec":{"command":["/csi-node-driver-registrar","--kubelet-registration-path=/var/lib/kubelet/plugins/org.democratic-csi.iscsi/csi.sock","--mode=kubelet-registration-probe"]}},"name":"driver-registrar","volumeMounts":[{"mountPath":"/csi-data","name":"socket-dir"},{"mountPath":"/registration","name":"registration-dir"},{"mountPath":"/var/lib/kubelet","name":"kubelet-dir"}]},{"args":["while true; do sleep 2; done;"],"command":["/bin/sh","-c","--"],"image":"docker.io/busybox:1.32.0","lifecycle":{"preStop":{"exec":{"command":["/bin/sh","-c","rm -rf /plugins/org.democratic-csi.iscsi /registration/org.democratic-csi.iscsi-reg.sock"]}}},"name":"cleanup","volumeMounts":[{"mountPath":"/plugins","name":"plugins-dir"},{"mountPath":"/registration","name":"registration-dir"}]}],"hostAliases":[],"hostIPC":true,"hostNetwork":true,"hostPID":false,"nodeSelector":{"kubernetes.io/os":"linux"},"serviceAccount":"zfs-iscsi-democratic-csi-node-sa","volumes":[{"hostPath":{"path":"/var/lib/kubelet/plugins/org.democratic-csi.iscsi","type":"DirectoryOrCreate"},"name":"socket-dir"},{"hostPath":{"path":"/var/lib/kubelet/plugins","type":"Directory"},"name":"plugins-dir"},{"hostPath":{"path":"/var/lib/kubelet/plugins_registry","type":"Directory"},"name":"registration-dir"},{"hostPath":{"path":"/var/lib/kubelet","type":"Directory"},"name":"kubelet-dir"},{"hostPath":{"path":"/etc/iscsi","type":"Directory"},"name":"iscsi-dir"},{"hostPath":{"path":"/var/lib/iscsi"},"name":"iscsi-info"},{"hostPath":{"path":"/dev","type":"Directory"},"name":"dev-dir"},{"hostPath":{"path":"/lib/modules"},"name":"modules-dir"},{"hostPath":{"path":"/etc/localtime"},"name":"localtime"},{"hostPath":{"path":"/run/udev"},"name":"udev-data"},{"hostPath":{"path":"/sys","type":"Directory"},"name":"sys-dir"},{"hostPath":{"path":"/","type":"Directory"},"name":"host-dir"},{"name":"config","secret":{"secretName":"zfs-iscsi-democratic-csi-driver-config"}},{"configMap":{"items":[{"key":"extra-ca-certs","path":"extra-ca-certs.crt"}],"name":"zfs-iscsi-democratic-csi"},"name":"extra-ca-certs"}]}}}}
  creationTimestamp: "2025-07-16T13:20:11Z"
  generation: 4
  labels:
    app.kubernetes.io/component: node-linux
    app.kubernetes.io/csi-role: node
    app.kubernetes.io/instance: zfs-iscsi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: democratic-csi
    helm.sh/chart: democratic-csi-0.13.7
    velero.io/backup-name: migrate
    velero.io/restore-name: migrate-20250716081927
  name: zfs-iscsi-democratic-csi-node
  namespace: democratic-csi
  resourceVersion: "93350"
  uid: b983ac80-3bc5-4073-a6fa-13479a32d8aa
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: node-linux
      app.kubernetes.io/csi-role: node
      app.kubernetes.io/instance: zfs-iscsi
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: democratic-csi
  template:
    metadata:
      annotations:
        checksum/configmap: 6aec39faec18176138f529a4ae68702ec821b436b11e320a799f22eeb85ddc54
        checksum/secret: be8a704348953ac7de0579f3cd7d70d610a56e26228303d217a2f240d7f79916
        kubectl.kubernetes.io/restartedAt: "2025-07-16T12:57:57-05:00"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: node-linux
        app.kubernetes.io/csi-role: node
        app.kubernetes.io/instance: zfs-iscsi
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: democratic-csi
    spec:
      containers:
      - args:
        - --csi-version=1.5.0
        - --csi-name=org.democratic-csi.iscsi
        - --driver-config-file=/config/driver-config-file.yaml
        - --log-level=info
        - --csi-mode=node
        - --server-socket=/csi-data/csi.sock.internal
        env:
        - name: CSI_NODE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NODE_EXTRA_CA_CERTS
          value: /tmp/certs/extra-ca-certs.crt
        - name: ISCSIADM_HOST_STRATEGY
          value: nsenter
        - name: ISCSIADM_HOST_PATH
          value: /usr/local/sbin/iscsiadm
        image: docker.io/democraticcsi/democratic-csi:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - bin/liveness-probe
            - --csi-version=1.5.0
            - --csi-address=/csi-data/csi.sock.internal
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 15
        name: csi-driver
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        terminationMessagePath: /tmp/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
        - mountPath: /var/lib/kubelet
          mountPropagation: Bidirectional
          name: kubelet-dir
        - mountPath: /usr/local/etc/iscsi
          mountPropagation: Bidirectional
          name: iscsi-dir
        - mountPath: /var/lib/iscsi
          mountPropagation: Bidirectional
          name: iscsi-info
        - mountPath: /lib/modules
          name: modules-dir
          readOnly: true
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /run/udev
          name: udev-data
        - mountPath: /host
          mountPropagation: Bidirectional
          name: host-dir
        - mountPath: /sys
          name: sys-dir
        - mountPath: /dev
          name: dev-dir
        - mountPath: /config
          name: config
        - mountPath: /tmp/certs
          name: extra-ca-certs
      - env:
        - name: BIND_TO
          value: unix:///csi-data/csi.sock
        - name: PROXY_TO
          value: unix:///csi-data/csi.sock.internal
        image: docker.io/democraticcsi/csi-grpc-proxy:v0.5.3
        imagePullPolicy: IfNotPresent
        name: csi-proxy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
      - args:
        - --v=5
        - --csi-address=/csi-data/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/org.democratic-csi.iscsi/csi.sock
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /csi-node-driver-registrar
            - --kubelet-registration-path=/var/lib/kubelet/plugins/org.democratic-csi.iscsi/csi.sock
            - --mode=kubelet-registration-probe
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: driver-registrar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
        - mountPath: /registration
          name: registration-dir
        - mountPath: /var/lib/kubelet
          name: kubelet-dir
      - args:
        - while true; do sleep 2; done;
        command:
        - /bin/sh
        - -c
        - --
        image: docker.io/busybox:1.32.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - rm -rf /plugins/org.democratic-csi.iscsi /registration/org.democratic-csi.iscsi-reg.sock
        name: cleanup
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /plugins
          name: plugins-dir
        - mountPath: /registration
          name: registration-dir
      dnsPolicy: ClusterFirst
      hostIPC: true
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: zfs-iscsi-democratic-csi-node-sa
      serviceAccountName: zfs-iscsi-democratic-csi-node-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins/org.democratic-csi.iscsi
          type: DirectoryOrCreate
        name: socket-dir
      - hostPath:
          path: /var/lib/kubelet/plugins
          type: Directory
        name: plugins-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: Directory
        name: registration-dir
      - hostPath:
          path: /var/lib/kubelet
          type: Directory
        name: kubelet-dir
      - hostPath:
          path: /usr/local/etc/iscsi
          type: ""
        name: iscsi-dir
      - hostPath:
          path: /var/lib/iscsi
          type: ""
        name: iscsi-info
      - hostPath:
          path: /dev
          type: Directory
        name: dev-dir
      - hostPath:
          path: /lib/modules
          type: ""
        name: modules-dir
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
      - hostPath:
          path: /run/udev
          type: ""
        name: udev-data
      - hostPath:
          path: /sys
          type: Directory
        name: sys-dir
      - hostPath:
          path: /
          type: Directory
        name: host-dir
      - name: config
        secret:
          defaultMode: 420
          secretName: zfs-iscsi-democratic-csi-driver-config
      - configMap:
          defaultMode: 420
          items:
          - key: extra-ca-certs
            path: extra-ca-certs.crt
          name: zfs-iscsi-democratic-csi
        name: extra-ca-certs
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
  observedGeneration: 4
