---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: mosquitto
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-iscsi-csi
  resources:
    requests:
      storage: 1Gi
