---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret
  namespace: mosquitto
stringData:
  username: ${EMQX_NAME}
  password: ${EMQX_SECRET}
  ha_username: ${MQTT_HA_USER}
  ha_password: ${MQTT_HA_PASS}
