---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy1
spec:
  externalIPs: true
  loadBalancerIPs: true
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: ingress-pool
  namespace: networking
spec:
  blocks:
    - start: "${CILIUM_LB_INGRESS_START}"
      stop: "${CILIUM_LB_INGRESS_STOP}"
  serviceSelector:
    matchLabels:
      lb_pool: ingress
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-pool
  namespace: networking
spec:
  blocks:
    - start: "${CILIUM_LB_DYNAMIC_START}"
      stop: "${CILIUM_LB_DYNAMIC_STOP}"
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: reserved-pool
  namespace: networking
spec:
  blocks:
    - start: "${CILIUM_LB_RESERVED_START}"
      stop: "${CILIUM_LB_RESERVED_STOP}"
  serviceSelector:
    matchLabels:
      lb_pool: reserved

