---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app promtail
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: *app
      version: "6.16.6"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  values:
    config:
      clients:
        - url: http://loki-headless.monitoring.svc.cluster.local/loki/api/v1/push
