---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi-nfs
  namespace: democratic-csi
spec:
  interval: 1m
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.1
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  values:
    csiDriver:
      name: "org.democratic-csi.nfs"
      fsGroupPolicy: File
    driver:
      config:
        driver: freenas-nfs
        httpConnection:
          allowInsecure: true
          apiKey: "${DCSI_API_KEY}"
          host: "${NAS_IP}"
          port: 80
          protocol: http
        sshConnection:
          host: "${NAS_IP}"
          password: "${DCSI_PASS}"
          port: 22
          username: "${DCSI_USER}"
        zfs:
          cli:
            sudoEnabled: true
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetParentName: tank/k8s/nfs/v
          datasetPermissionsGroup: 0
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetProperties:
            org.freenas:description: '{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{
              parameters.[csi.storage.k8s.io/pvc/name] }}'
          detachedSnapshotsDatasetParentName: tank/k8s/nfs/s
        nfs:
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareHost: "${NAS_IP}"
          shareMapallGroup: ""
          shareMapallUser: ""
          shareMaprootGroup: root
          shareMaprootUser: root

