---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tandoor
  namespace: tandoor
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      tandoor:
        containers:
          app:
            image:
              repository: vabene1111/recipes
              tag: latest
            env:
              SECRET_KEY: "${TANDOOR_SECRET_KEY}"
              DB_ENGINE: django.db.backends.postgresql
              POSTGRES_HOST: immich-cnpg-cluster-rw.immich.svc.cluster.local
              POSTGRES_PORT:
                valueFrom:
                  secretKeyRef:
                    name: immich-cnpg-cluster-app
                    key: port
              POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: immich-cnpg-cluster-app
                    key: username
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-cnpg-cluster-app
                    key: password
              POSTGRES_DB:
                valueFrom:
                  secretKeyRef:
                    name: immich-cnpg-cluster-app
                    key: dbname
    service:
      app:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:chef-hat"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
        - host: "tandoor.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "tandoor.${SECRET_DOMAIN}"
          secretName: tandoor-tls
    persistence:
      static:
        existingClaim: tandoor-static
        globalMounts:
          - path: /opt/recipes/staticfiles
      media:
        existingClaim: tandoor-media
        globalMounts:
          - path: /opt/recipes/mediafiles
