---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-static
  namespace: tandoor
#labels:
#    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-media
  namespace: tandoor
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

