---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
  namespace: seerr
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      sonarr:
        containers:
          app:
            image:
              repository: ghcr.io/seerr-team/seerr
              tag: latest
            env:
              LOG_LEVEL: debug
              TZ: "America/Chicago"
              PUID: "1000"
              PGID: "1000"
              UMASK: "000"
            resources:
              requests:
                cpu: 500m
                memory: 2048Mi
              limits:
                memory: 16Gi
    ingress:
      main:
        enabled: true
        className: "nginx"
        labels:
          external-dns-cloudflare: enable
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:jellyfish-outline"
        hosts:
        - host: "seerr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "seerr.${SECRET_DOMAIN}"
          secretName: seerr-tls
    persistence:
      config:
        existingClaim: seerr-config
        globalMounts:
          - path: /app/config
            readOnly: false
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
    service:
      seerr:
        enabled: true
        ports:
          primary:
            enabled: true
            port: 5055
            protocol: TCP
            targetPort: 5055
