---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
  namespace: seerr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: seerr
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    config:
      persistence:
        volumeName: seerr-config
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"

        #external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"

        external-dns/is-public: "true"
        hajimari.io/enable: "true"
        hajimari.io/icon: "mdi:jellyfish-outline"

        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"

      hosts:
      - host: "seerr.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "seerr.${SECRET_DOMAIN}"
        secretName: overseerr-tls
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi

