---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1vcv85qmhme0zc9ncdvgw9mq0cr2fjewts3ne2g8xnngvpktwapxq5x9reu
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1vcv85qmhme0zc9ncdvgw9mq0cr2fjewts3ne2g8xnngvpktwapxq5x9reu
