apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app zwave-js-ui
  namespace: zwave-js-ui
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      nodeSelector:
        feature.node.kubernetes.io/usb-02_1a86_55d4.present: "true"
    controllers:
      zwave-js-ui:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: zwavejs/zwave-js-ui
              tag: latest
              pullPolicy: IfNotPresent
            env:
              PORT: &port 8091
              TZ: "America/Chicago"
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
          websocket:
            port: 3000
    ingress:
      app:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:z-wave"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
          - host: &host "zwave.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: zwjs-tls
    persistence:
      config:
        existingClaim: zwave-js-ui-config
        globalMounts:
          - path: /usr/src/app/store
      usb:
        enabled: true
        type: hostPath
        hostPath: &device /dev/serial/by-id/usb-1a86_USB_Single_Serial_58E3037630-if00
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/zwave

