---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      nodeSelector:
        feature.node.kubernetes.io/usb-ff_10c4_ea60.present: "true"
    controllers:
      zigbee2mqtt:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: latest
              pullPolicy: IfNotPresent
            env:
              TZ: "America/Chicago"
              ZIGBEE2MQTT_DATA: /config
              ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
              ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ${quote}${Z2M_NETWORK_KEY}${quote}
              ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: 60
              ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: 2000
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: "false"
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
              ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API: "true"
              ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: 8080
              ZIGBEE2MQTT_CONFIG_FRONTEND_URL: "https://zigbee.${SECRET_DOMAIN}"
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: 60
              ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://emqx-listeners.emqx.svc.cluster.local.
              ZIGBEE2MQTT_CONFIG_MQTT_VERSION: 5
              ZIGBEE2MQTT_CONFIG_MQTT_USER:
                valueFrom:
                  secretKeyRef:
                    name: emqx-secret
                    key: user_1_username
              ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: emqx-secret
                    key: user_1_password
              ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "true"
              # This is going to have to change to whatever the device actually is.
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: &device /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_9c3a01775f51ef11a4eb378ccc32aab1-if00-port0
              # This may differ depending on what your adapter is, check the docs
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: "zstack"
              # ZIGBEE2MQTT_CONFIG_DEVICES: devices.yaml
              # ZIGBEE2MQTT_CONFIG_GROUPS: groups.yaml
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 8080
    ingress:
      app:
        enabled: true
        labels:
          external-dns-pihole: enable
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:zigbee"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
          - host: &host "zigbee.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: z2m-tls
    persistence:
      config:
        existingClaim: zigbee2mqtt-config
      usb:
        enabled: true
        type: hostPath
        # Same as above, this and the one below it must change to match your actual device
        hostPath: *device
        hostPathType: CharDevice
        globalMounts:
          - path: *device
