# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ZekqDvqvLBozpNDaFx0mkil9/IIH0ArZ,iv:wRtkD9fecmbaiH8lwtAJaRYZIzo1A0U5JBQvCJs+WiY=,tag:nnAb+OihKpCBFd9Df9yMog==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:+rx7cC5gevd/RXYLcBwCPoXd6t1B7cwXo2DwhgggaWSK4lC45w==,iv:2GXIlnO1tFZIwvmZFA63RnOXDc1Q2Vj+cDN5m6uSWmM=,tag:rCcyHgj9f3tO6T2HCAF62Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:XuZHV6q9TEa+mP/xoA==,iv:YGsl7uDiY/9GAXtTL5uEourUT6Fux92tVzzQsddQfmg=,tag:4cjVeKNXLphQ63wrF/km8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vcv85qmhme0zc9ncdvgw9mq0cr2fjewts3ne2g8xnngvpktwapxq5x9reu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcll2VU9vTmFkUmpOa3JG
            d1JYYkZNRWFLRTgybVZvOE16RlRYQkVvNW1jCnJQSkJTYmhqYUlTOHdDZDJrSkNR
            UlZiRVVPZGJUeUpURmViYk5YQWFvT2sKLS0tIFdyYWd0VzZVVXBwWnBIMlNHcVZ6
            VHd6OWpiM3FNRzdEUEZDNTF5amtmTUUKA6RnbBYueTz5AVmaOaiIOkakfiIq9pXI
            Pm2Eo+4OJHqXdHbK20gEyOwPHdRZoSgtm4kX1zsU2tnRnAM2Tn1JNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-13T19:50:26Z"
    mac: ENC[AES256_GCM,data:9mW+nFs6iz/VbJb3Bmpa86OIdb8BUqamMyYLvJyy9U5TbAxUZaKCYz1P9Y5AHWc4TSVK2Hz/DW7qkdt0TWDwBYLTQYJv+h1tSZIKQqKo/3s18rbv1SLvPjXM7ad992ssKOqMshqfX6+TO1GZZII66kCKwcmlD9a0BXfvtXIBR2I=,iv:WE/T2qZVulVbQikds4cxWfv/xQbgDFv4lN8G4W0/ytY=,tag:zEXJYF2VKs2rDXCthwBlTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
