---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tautulli
  namespace: tautulli
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      tautulli:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/tautulli
              tag: rolling
            env:
              TZ: "America/Chicago"
              TAUTULLI_HTTP_BASE_URL: "https://tautulli.${SECRET_DOMAIN}"
              TAUTULLI_HTTP_PORT: &port 80
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:animation-play"
        hosts:
        - host: "tautulli.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "tautulli.${SECRET_DOMAIN}"
          secretName: tautulli-tls
    persistence:
      config:
        existingClaim: tautulli-config
      tmpfs:
        type: emptyDir
        advancedMounts:
          tautulli:
            app:
              - path: /config/logs
                subPath: logs
              - path: /tmp
                subPath: tmp
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          app:
            port: *port
