---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: radarr
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      radarr:
        containers:
          app:
            image:
              repository: linuxserver/radarr
              tag: latest
            env:
              TZ: "America/Chicago"
              PUID: "1000"
              PGID: "1000"
              UMASK: "000"
            resources:
              requests:
                cpu: 500m
                memory: 2048Mi
              limits:
                memory: 16Gi
    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "weather-sunset"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
        - host: "radarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "radarr.${SECRET_DOMAIN}"
          secretName: radarr-tls
    persistence:
      config:
        existingClaim: radarr-config
      scratch:
        enabled: true
        type: nfs
        server: 192.168.86.5
        path: /srv/scratch
        globalMounts:
          - path: /media/scratch
      tank:
        enabled: true
        type: nfs
        server: 192.168.86.2
        path: /mnt/tank/media
        globalMounts:
          - path: /media/tank
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      radarr:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 192.168.86.66
        ports:
          primary:
            enabled: true
            port: 7878
            protocol: TCP
            targetPort: 7878
