---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: nzbget
spec:
  interval: 1m
  chart:
    spec:
      chart: nzbget
      version: 12.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: linuxserver/nzbget
      tag: latest
    env:
      TZ: "America/Chicago"
      PUID: "1000"
      PGID: "1000"
      UMASK: "000"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:file-download"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
        - host: "nzbget.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "nzbget.${SECRET_DOMAIN}"
          secretName: nzbget-tls
    persistence:
      config:
        enabled: true
        existingClaim: nzbget-config
      scratch:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.86.5
            path: /srv/scratch
        mountPath: /data/scratch/nzbget
        subPath: nzbget
    podSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi
    service:
      nzbget:
        enabled: true
        nameOverride: nzbget
        type: LoadBalancer
        loadBalancerIP: 192.168.86.64
        ports:
          primary:
            enabled: true
            port: 6789
            protocol: TCP
            targetPort: 6789
