---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config
  namespace: nzbget
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

