---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx-operator
  namespace: emqx-operator-system
spec:
  interval: 15m
  chart:
    spec:
      chart: emqx-operator
      version: 2.2.22
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

