---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app emqx-operator
  namespace: &namespace flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: emqx-operator-system
  interval: 1h
  path: ./cluster/apps/emqx/operator
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app emqx-cluster
  namespace: &namespace flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: emqx-operator
      namespace: *namespace
  healthChecks:
    - apiVersion: apps.emqx.io/v2beta1
      kind: EMQX
      name: emqx
      namespace: emqx
  interval: 1h
  path: ./cluster/apps/emqx/cluster
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
    substitute:
      quote: '"' # double quote var
