---
apiVersion: v1
kind: Namespace
metadata:
  name: emqx-operator-system
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: emqx
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
