# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:iVKIClgpt+KFLFgpK8mund7MHtj/U4scWq4JI/8CJBy65Q9faw==,iv:qoMekwaTuyX5nTxYlittYNytyyvd+/JCpSKuAihpl+M=,tag:eWyXfmYPuZMOaqKdk1i4Ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vcv85qmhme0zc9ncdvgw9mq0cr2fjewts3ne2g8xnngvpktwapxq5x9reu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRHdMbFE0ZDRmMGRZQUlN
            Vnp5d0h1SDJIejhhV3E2MVFWMVhjYjRDWVN3CktxWkVvMjJLNCsvdWR5MHJVdXhx
            MTJHc2toMDRyUGtPbFlmNDZqNkMxMTQKLS0tIEFINjJMVmlaMCtHTkVsRnY4QlE3
            dDdURHBmSVVZVVliUW4rUE1TZFhhclUKDJyYdvKY++4i0KijTri+yFkdY7ZDMhfU
            6Pfkcdf19TQMLruGs+hK+5RNJlJBadJpxZ+S5OqKyK/t0lZAN75bZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-13T20:05:39Z"
    mac: ENC[AES256_GCM,data:J732qmmbz/O+VQYd7N+dLOyzcICu60817i00sQJaidjB0zBfIwrgRQyB/SiIf1Axw1euxiYZuma6dBuLhAuRlA+fOeFkn5JiCJO0yaS4nIbKVUmzacCUXIaSe9aGSpwYv4w9oaOk9bQvzUkKtxc8RkHFA9Uxyp4jK6GEbHdo+Do=,iv:gBj6QpSF+NRx/xZLJdW5ndPvzk2UWu+TzBLA4NHOAQQ=,tag:a6ocz1KkxY46A1mRZhiCAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
