# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:EQKWcrNhXksh7X+WtMqlBu+VIJ1V7yiF,iv:dmvNzZMV9cJO2N374aASLd578IBFwkXee0aFrc+g+d0=,tag:koAhyWkSZGmE+R9m8UG36w==,type:str]
    api-key: ENC[AES256_GCM,data:jBLW1R3yfy/I0teoNo8vUo4RVTPOsEWH2jy5ePuVto+XJQXqNg==,iv:WwvbbC9SMPs7CcUfB5Vc8X5cAId5G4iMb69OKizSSmE=,tag:lCaWf2Fad6SGKCsVMx9JOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vcv85qmhme0zc9ncdvgw9mq0cr2fjewts3ne2g8xnngvpktwapxq5x9reu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSDhHaDhHMng0VFhhcDdD
            WGVTY0d2WVJrSkFSUVhmekdTQ2U5SzR3a2hvCjJrTG5pZ1VnNWFqOFYxcG9lemEv
            YWYrQnZCbisveXBISFVIR2V6enRRdWsKLS0tIEVmZitZVjhZZjNHRW1NQkgxaVN4
            Yk4xa0hvZ21QbjQ2a0xGT2lHZXZDbkkKrpkpwlB5VBnyUB6wAyfT4YkM6WqJAvwV
            dNuQhCLhD9jckhciLEDhNV4klpImRDDbplHKZdWVasK3pktkUn3bsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-13T19:50:26Z"
    mac: ENC[AES256_GCM,data:XzSCr85Ze6ZIE6tf4ZJX36SqddYHUETBiVDf4R3RlnxsBqnTpYhzCAtdvUQyO9N6BNHWD6BeE7PpPX1zOHQqXeG938f4UBEyFqOjkcBwhwghywO8xfxsdfKkqQD8ot0Sf7N5imzy3KFvsvHdBCWocjiBqNE9AoTfLTcDMpEpNSg=,iv:En5oQu6MLuEqEAmmosMV1tzeAEsf6ofbk5qBaZeIOYw=,tag:o4IYUFxGM9DdmHkxHnFKIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
