# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:y30jRxi9+Qw=,iv:o5DHhmGsvL9bvT/U78jFQ96YG9Zw6ErAcE0oBxmvu74=,tag:wWCYwjVuM1hOry6aaPxI5Q==,type:str]
    SECRET_DOMAIN_A: ENC[AES256_GCM,data:jS/0gilUEjo=,iv:ehemOn7Dm1UAHhzPWLRlqrA95Csv9PxR8cndS752x8M=,tag:hmC0mvm9cqkpdWiW/HxKYA==,type:str]
    SECRET_DOMAIN_B: ENC[AES256_GCM,data:1QiOHzkryTkA,iv:6WN4bD9r7dCNH9PVMJ1xXG3lqBxdq2BBH4N9Nh6+8f4=,tag:JyFecWzm1wGnu26I3KnGUA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:sqhHkF6jg599OF0D7IX3FuuMINw2fH9R,iv:srO4QMNefZt7XhWeBRvWHG6Am90bqUzuC04HHmowdZQ=,tag:NDwhNSS7VEvGBTPibzVV4g==,type:str]
    NAS_IP: ENC[AES256_GCM,data:CCNz3k9E3sxe3lAz,iv:hcVsI7Yvp2siO93JzAeBIqmEZZk8hmxEkHhXHOGAyCY=,tag:AJHZFf9fS7Dk9YDsbJ7bgg==,type:str]
    DCSI_API_KEY: ENC[AES256_GCM,data:A1epNT+T9ThksJ8CP/Z9OOkPUkoj0HIEoVLoPL/cHOm7Z9Qo6PhYWohHD05V8iMShp5AbK0xM2YvBd4/CycDxTq/,iv:TN6qrzi6Da5gzCLcmtZ96qOGsqiWlhNI2vK2hFW40Kk=,tag:e8/Y10xcLT+tdRoPrGYOnA==,type:str]
    DCSI_USER: ENC[AES256_GCM,data:5WoA,iv:4QqjgfobSAIIB7jWkIAEFGc5Rao9eaHf/jQxWfn6qnE=,tag:Es6RBSMGeryiXlxjOUmuZQ==,type:str]
    DCSI_PASS: ENC[AES256_GCM,data:Rqf+tMG2BPQHhw==,iv:c75YdrBkQ7yqAniaIKCPeutPgsl9zVr6hKi5/l7auXA=,tag:aP3X/zm+s+2jLq9MIqrhYg==,type:str]
    Z2M_NETWORK_KEY: ENC[AES256_GCM,data:0jGatqJj7IjcHCczn8IhRozpRxrNoIjKNY+Da6VPyb+v0mkiuSbDtdXwNSuwLPDpSO7aTbg32BbP3EAqGeTcPAiwkXXcMlnV,iv:Kcq7FvbBXcDiGKSEbUEc/sbKUYgf41xbraO3q817Wmg=,tag:AfuhpTzOMuto5db/P1rJ/g==,type:str]
    EMQX_NAME: ENC[AES256_GCM,data:4ieGBqaAJMw=,iv:9xjvq1KVq9/+P6LAFWpPgqQZ0B9uP9v5voEPrFLPayk=,tag:ZD4DRMojV4vxDwvtvB9kBg==,type:str]
    EMQX_SECRET: ENC[AES256_GCM,data:/SnVuZcUcE5GTbM6WGg=,iv:k18zv5HPH3gvnqODwDtUkeNr0hLLllZi+jpzTvnz/jA=,tag:kehWMjRPlbptR0R/UI8z8w==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:P0O7Vwj1C7hp9dG0xZBohlEPNTG1oaki,iv:UtNR1+R6+4QRuPSLGOYD7Dcxw1B1ZiWCPItr43D6p6Y=,tag:KfI/oqT7Sw1kU8Ff4nMnJw==,type:str]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:aXiMdzW/KyM=,iv:TiQ7x7WBF/jwnKb8/WAFC22+PRyrt5QnZ1+Y/aLr15w=,tag:dEguOrzqQMWmoNXAAjBujw==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rXKXQsJF9yvR44nfIu4=,iv:J5Xvcv57jZca0dVwOcREz/fM/XR40x6v4ICVm5SJ7f4=,tag:xbzuWrPjWTVmWNBNfvi1YQ==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:E4xQWo8AdK4TbNn+9YUXrPDWkQFDB5GLHE1PQ1aZChE=,iv:C4ntqkHLp2gfWKTegAH6x1hvpZadKcb/Dl7jrbwVf2E=,tag:RJMk9vY6YruUPG611H48dA==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:E0PeakjWEe1lCUefceL+P7vqWc1MmHDQfNutDVhtpuA=,iv:FruF4cYrZgBkmxj7EBYFl/DnztGn39OCJM5l8f0Jnro=,tag:ZVm5iAnS6ueSFTugK6lDMw==,type:str]
    TANDOOR_SECRET_KEY: ENC[AES256_GCM,data:HaNvyw+waFQZBrv83ED1Q249fWECzrAKhRTOJEctwHQvDlM5cLk5+BDm7wLOROlD8IuGl72IS3TIry7muAfSgg==,iv:qI2oFk4cGGOqguh+IETP4qg4EszbBtJfym++9O6OfyE=,tag:hE2WemTJauUI2yESjL+3TA==,type:str]
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:kI4qcQ5JQNon6AEKkW5QTj7lQMEEVOg6nncYqStGb+BJ+WGhtwpx9KDv5lw=,iv:5ay2cBs7DTND/iQ6VOhajFEWi8Jp26yOK+yzahR81/M=,tag:dwRijSsO1bZt2j1cMfWkog==,type:str]
    PIHOLE_SERVER: ENC[AES256_GCM,data:gMo0buGi14qh4qSh,iv:cBLbbaFy6RKy2zxZG5XQ71b7rejl+wZvq7rEyF8oEKA=,tag:R0bXegXvMvkGqvEDWYSzWA==,type:str]
    PORKBUN_API_KEY: ENC[AES256_GCM,data:UBc3iVbJQZURQLxDxwZ8Ebqcx8mna3xJtEI6WKrknnTaiy94pwAhTIVTOB/HY+i7APQh5IA0YAy5BT/B+1LTn0yqEjU=,iv:ocdd0ndr3oJuI9pe+9mP6HU1fORHauPi880KVahLXVs=,tag:9x22+4zF5mgnD6D2kiChuw==,type:str]
    PORKBUN_API_SECRET: ENC[AES256_GCM,data:1S7t6n7uHV227V6F2uzrAOAPr27iNdlIUL0+cf8ePuAD3H6RQKFN1VyeV/b9nYaqtILovvTy9dysqoOBThXxXsx2jaI=,iv:WfF5caOeBrTB9zAhU2JzHIzHEiGhAMzhf6RkUNYnzng=,tag:8w41/VVL7khts//2rbLRbw==,type:str]
    PRICEBUDDY_APP_KEY: ENC[AES256_GCM,data:VTa2/DNbVrN3fJELJDth/uX1lLAyZi515Hadzl/juMREKnmyqHmYF9DDxnQ5vMckm+Y5,iv:2zMsi7rR0+ItAUpeYdmL3cfuJ9h6st2wMBtmS3qRp4Y=,tag:qc3Dl+r2VCOl2hGqMsvJaw==,type:str]
    PRICEBUDDY_DB_PASSWORD: ENC[AES256_GCM,data:eJECyaff7rK6CbmNCj3blJA1MvhfeeUDKpUuPDHOtexYvGAN4SNNAgNXB+cYTr83IebSdz1C0pqUygr1yduaEw==,iv:+aLKRfK6Sxpst7UFzpMwjO2ZL3D38n6Hii/bRy8HbDA=,tag:XS4JNwMDmkfxKkj5Nj+dwQ==,type:str]
    PRICEBUDDY_APP_USER_EMAIL: ENC[AES256_GCM,data:aiOeikHzDBwCJDisyMPwkzhn5g==,iv:jPpNSN2P/bX6y2znmoQh/bsvmkA6s5Nyf7cc7FH5670=,tag:uRWZLScaR9UcMDre90prfA==,type:str]
    PRICEBUDDY_APP_USER_PASSWORD: ENC[AES256_GCM,data:VAvJiGmaRQS22T4PebGrhfb7kaxf/yk2FtXez5B4RgcvBWCNfTHarERcI9xGbbqauQjgIJybQvE7nRDt1TcsUw==,iv:cnYq+f7z7rgRa1vtJ7ZEVXKtl0UxJhOTO3p5lznu7F4=,tag:VB+uGmSjVLEjXaH9u0R+rg==,type:str]
    PRICEBUDDY_MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:zQs0/dJAeIfMW6qTLOLOoTLKZm0naF3OcZ72CTbylRn5MS0m6MFQqkzrGDyClOYy+3saFvLiIOrFURDszG8ZKA==,iv:nKeUGZmiancWYGTo+m0x2khlJFc6Wpuglb5WJQQjGhg=,tag:RF9L+J4kCbkXVxdm9fPPRA==,type:str]
sops:
    age:
        - recipient: age1vcv85qmhme0zc9ncdvgw9mq0cr2fjewts3ne2g8xnngvpktwapxq5x9reu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2R1VlSm15TzF2bHNYUkoz
            UXlka2orcWlBWEY5VXpvbTV1S283alBKUTFZCk9SdzFGTVRQN3dMSU1xWFJvdDJs
            alJtc3pneE52M1ROK2doaGt2YnBoZHcKLS0tIHZsRU1LR0htOVhlVkg3a2xPZXJ3
            UXBsUkdZL1k1MFgzVnVaeXhGeUp5NkkK7IDLfqy7JJ1mO2GDh2zS5t4Oh7qxB23F
            JJ2i+hWMKSMyugeRnG6jnr56uHvB67mWbfwQzy2asepk6Yo5aRt9ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T16:26:55Z"
    mac: ENC[AES256_GCM,data:5g/tevH/KOKJY4n7mes2UzgNwx2KHDW0kS77aSwD7w1sFnxdbQC3XT8RzEDUCng1h4twDuDkzzNeM0oBsnuI6DdtfmLYxW06wwqK75StrrKzpW/pTi/CA47edMma5H03WOnR81G0ckOvPn5H/3s28d2QGAWdOQbSCfcJiwrm8Kk=,iv:B7iLV6d4bFN4sw0oqCkW/57EKQJrqhzkSiNCehHYyAo=,tag:PfgSTvzK15O9hqV9aUnJCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
