# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN_A: ENC[AES256_GCM,data:YcZ+EmjZEw4=,iv:BgIu3cxZy6sR10nk3dva5UZ5gi4ztDhWwYMk07W9o4M=,tag:tERPGQMoZjM5tUFM6XOwCg==,type:str]
    SECRET_DOMAIN_B: ENC[AES256_GCM,data:/0FNyKJJ2lD2,iv:BYQk3Tz8/ddD8yXhIAh/X/XevIuMU4y+UR9iXtcbqEY=,tag:fX0e9D3crXHVSl1/1tRkiQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:0esyzjwPdPdJ75y/r2B63xNCBP1Y47im,iv:e+/1PAvxMD3TKpn+nxrxNaQcRDL9/K+KQ2XkprvxZZ8=,tag:3aFgnpAJX3w1TvJPC4BLtw==,type:str]
    NAS_IP: ENC[AES256_GCM,data:4s32LsIiKaFcYxH/,iv:QfxCySDptZjiRyOrLEytRH2K4Pqf1r447QJKIuMjQM8=,tag:kIR5IxPxUJHTPyYBfJ24Dw==,type:str]
    DCSI_API_KEY: ENC[AES256_GCM,data:5Av4GjiAUYBQQT0SRYYy66J2UdV0zn7alqgG4eoPC/N/Wt+4CZhsog6b7KQExp80jEV8lU/xZJJwwfYlMKJ5HYjv,iv:j8NuzL3aOfI74iVY1HA/6g263G/yLNrpobpkDSH6lnM=,tag:/IHhYF79H08Q1q7jwbP2uw==,type:str]
    DCSI_USER: ENC[AES256_GCM,data:wN7I,iv:qgcir3mGsE1jN+Sl/ao4yhJY4sk3AZtiyaNMUZ7QcvI=,tag:SjD3adyzUhpGxkJd1RiOhA==,type:str]
    DCSI_PASS: ENC[AES256_GCM,data:Zu55xAVs4gbMyg==,iv:lTQB6aicUq6+qrvDSCbmZDi6ULxW0X1P7VWAJlWelbM=,tag:rK8yZuQea7GGyBSKJOmrTg==,type:str]
    Z2M_NETWORK_KEY: ENC[AES256_GCM,data:16iLE8G7yVK6RINPWJ2E99EfVEUzTovhBvduJWbgbQWUnwIBK97LXqZZuV0mxlNuJr5I6MAMNqbvux1a41IZNDnC/rV0JN+V,iv:BA9VaOJiZKg3z2F8zD9RRXHltMOWwGJTuaBXwbEcQ1g=,tag:ypO750vd3NaKgigfVf0h5g==,type:str]
    EMQX_NAME: ENC[AES256_GCM,data:vSBZVzxY53g=,iv:FRzz2GSTkk0K85K4fI3kp/QpZxiAWotUd40vvFDcFns=,tag:2vP935pM3l4e+BbL7PJXQQ==,type:str]
    EMQX_SECRET: ENC[AES256_GCM,data:D5AWseighMdja4Ybh2M=,iv:bKXqGoqtuS3/P6YSH5JT9z1j0RerCvEPeIc5deTASl4=,tag:KFReriaz6pzjC8PxpfI3BA==,type:str]
    MQTT_HA_USER: ENC[AES256_GCM,data:yjDvkrWx/A==,iv:77l3cki9gw3IPrk1/2tCe2Jyh7A7gOGXkp/+1OlTHf8=,tag:KJ52p9rVLOFhIFGs+2pqVg==,type:str]
    MQTT_HA_PASS: ENC[AES256_GCM,data:MfKChR43dK7kD8X+MV716JbvbWuem55KjYQriuItkbs=,iv:JJmq9PKuVc/BFHMBO+66djLyBrIIc7kC5HwnrVj4SWk=,tag:bekUzcPZlFwuGNwHjvVChw==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:F8yl5ldt8nApdZ1TSEGSUS5m7BSiSJuX,iv:a9gu8ITpLvPT44cD5tkrFaohykulDppUeO9joAIxLv4=,tag:NUCRd5xoe8K0iQvRc+ArIQ==,type:str]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:x6ryaE1MO1A=,iv:62dSxGO0x364eLczlaPDsW5U0v8qhh9fTFaoOtj5eyI=,tag:a8CTR0ht2xjpPYw5oB50sA==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:5alkmrpE1xwA+PHCXRo=,iv:FkXbYB54Voc4uDgM6mdrSxulC0Sgm/CIGH/TgxVCETQ=,tag:7dpUWmgIhA7+dAI5K+d3ng==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:jiZOMERzXGSjKPZtj3I86d+2XdqGd7FPLpvw8tUTL3E=,iv:VHCSRWzBxzLKQaSNpwWxTe6B4FwOFASfEwI/GvDqYTA=,tag:Ilb2p2bR5M8+E533Bnipcg==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:NJh9l88i7k27vkOfQl8dvEvw9DH5aKw6DioB2KxPRLU=,iv:4K4DwhrueiRlp/55jz2T0JdBsgf+AsQMrAvjqHSuVY0=,tag:t3CzZkN/hOzyzQNGRDfzIQ==,type:str]
    TANDOOR_SECRET_KEY: ENC[AES256_GCM,data:9RvLj9BA+T0Z9JinQaV715xX8pgbTzNl/LU5eDL42hI//fPMidzwExuKrLMHXtyOzk6mAXuqnVC1uT7izVsMnQ==,iv:m56rN596wL5+Qq16q3Ed4VR7Jy4mRAXZAABJwBm4zBQ=,tag:JGN2OGO9/d50TLjTmvnkYA==,type:str]
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:AmBD7vGQYEPfBAku2wlB+m2Rlz8MjGTc+Oouh7sk95zMRTQyfrINa9Gqiuk=,iv:PrYqFDY1T8XRCJWLXcRr4psnF6umtvqghUTamojDsK0=,tag:y6A4GvpKPRzOYXpaGjuvRA==,type:str]
    PIHOLE_SERVER: ENC[AES256_GCM,data:lQfCow1601ft2ugn,iv:tui+7V8UFqc38KQh5a40Ps9Lc4aGR+QVV/7gM/FOOk0=,tag:1TJJMb0xyz6g3PmRTKmi5Q==,type:str]
    PORKBUN_API_KEY: ENC[AES256_GCM,data:CL36nOBWXz5tMqCluBCq5q3woyryQ8ljtWZAD8QrTaoywclJ0mmPdc7ly/TjSeqXxC/YkBbgQ40e1BreGql/boNORZY=,iv:7w1GBthMVMD9DgfO00gqr+65tjphdzZo5OvCSyV8I2Q=,tag:u2hfQM+2Ht0nhCzZlZBAkA==,type:str]
    PORKBUN_API_SECRET: ENC[AES256_GCM,data:krbhR4r1J8ukbWMyCEOrI+VbbE7ARfNdYnvLzSd50G0SVdXPmJnWcmBc4BfOWMkjRf00gAqcXfJoTZ4kulqrH4Ez6O4=,iv:dRUJ4xz8e4lL0wXQNk0OokErzoZAiZNpjqT+3efDWgo=,tag:ve6RHpa90KvVfHI8I72Pow==,type:str]
    PRICEBUDDY_APP_KEY: ENC[AES256_GCM,data:+uqiH0NM6VE+A85NDtvXGShRUrFQbJ1q6zeV+VICVruShqBJc1AjlvYywW2CIQhKiLmT,iv:uqE/O4mJfIZZXBdaoxxJOWQ0l/wCLutN/PApyNsjcto=,tag:D2iuudAB5/ElxgFh5jWhXg==,type:str]
    PRICEBUDDY_DB_PASSWORD: ENC[AES256_GCM,data:q4etYYBWgbby6Mbox24eKU5q2uMfIfEliDgpSv85DDd3OcP524gR/4/RHHppKNJMjHUws8UEuc2kzPaiTUAH/A==,iv:3f4Ujow4sRUCOkckKIm6aT3tKxKUH2DxoQGnqpC2JGs=,tag:vyk/oGc70z9IgLxorKdvLQ==,type:str]
    PRICEBUDDY_APP_USER_EMAIL: ENC[AES256_GCM,data:zlOV2tNV8mmGHRjuHOffbQJVmQ==,iv:LDRlfCpQoD5ljSabuYElwkOcy4GCnDVZsxQPr15lwjA=,tag:pcrpa2ZN+XkO+NhYeIhkfQ==,type:str]
    PRICEBUDDY_APP_USER_PASSWORD: ENC[AES256_GCM,data:JIb47BfoNvRaWUyxz4yiwD/94dueL17qqK5uY4vaUynRY0iJk857H/SCA5waUBYkvX68PbPvgtF54YXRPhbwaw==,iv:V2a6q7o7ZW7gpoWhuv8HiyGJbJSAYtPru74t4R9SvEs=,tag:+qTII1A95S2xVHDlTCybew==,type:str]
    PRICEBUDDY_MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:A2qJLYtsFSk9p3MsBLFAaxboQ46dQ6LjsfcV3pWruK41zItGeLRrGZJ6mO9w2rDEANlGHf8u+s8oIs0HtLwZPw==,iv:kB/wXfWGcbNs2Aji4UE1N7l/a3ZIiX7YmCELGJF3pD8=,tag:9uqsdFX5XX/Y1128aK7bvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UFJ3cVpja2lVb21wejc0
            YzN6MmZHYWZSanlldjNZdDR0NHV6WWgrdkg4CmJzR0VnNjVnbmF6a0FBZVpIZlZQ
            UUt5MWJsWEIzZ0N1WVE4c3c1R1hNSUEKLS0tIDhubnozQm1ncWJpL0crNnhpSFNO
            UmVldnhYZ2ZuZVI3UXJEQWN3K05DUFEK1OXLTnyIehWBQWxQXoDRcMWT8zZKsLh6
            JeU8mLU1I4Vpqj4NXrxUYG7hAfWse2jrwsv+7bU+plpMZWCCx1mqtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vcv85qmhme0zc9ncdvgw9mq0cr2fjewts3ne2g8xnngvpktwapxq5x9reu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T19:27:45Z"
    mac: ENC[AES256_GCM,data:IIV93E+KvBbLf6iua7znXKNMPYD8R9TnL4zFhvoVdMyGTxr0y37VZU9kOB2thT9z44TBikXpkl1ipsOE/KcCCQoKGBOY/WQPj8Ay0KCNem5BHf7wj8DIvVQnita1M8vMHXZ48HcD5d89R3eP31htGBydhaLnein/4oVOXChQ44w=,iv:9S1cMTz0TbYj2XG8Ml2ab4k9q9EKMNuy86cl6TTE0rg=,tag:+arXj0Jfr7uFprPcHbw28A==,type:str]
    version: 3.13.1
