---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - helmrelease.yaml
  - namespace.yaml
configMapGenerator:
  - name: recyclarr-configmap
    namespace: recyclarr
    files:
      - recyclarr.yml=./resources/recyclarr.yml
generatorOptions:
  disableNameSuffixHash: true
