apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
    volumeMounts:
    - mountPath: /home/ubuntu/scratch
      name: scratch
  restartPolicy: Always
  volumes:
  - name: scratch
    nfs:
      server: 192.168.86.5
      path: /srv/scratch

