kind: Secret
ansible_user: ENC[AES256_GCM,data:rXSleg==,iv:7CsO9t8IsVrgmR0ezPwYQpcJkC7QMYQ/DF9MoXykW84=,tag:5L5LNyJMfI0b0Vps6BZ3Og==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:mamvx5igd3E=,iv:TWankUQ9PM3xZWxmiL0bBmb9kkDnECUlFsEibM+RQHU=,tag:7RpNerD01vRt/fvW6x1xmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vcv85qmhme0zc9ncdvgw9mq0cr2fjewts3ne2g8xnngvpktwapxq5x9reu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVDBMVGllMksvbUVXTHBX
            WGxHaExaM2pMTDZZdHZ1eENKT0lmYTc1QlRzCnFGK254UWIxQmVRU21xQkdvSmQx
            K1hSRzBxTm92dDZtRzMrZTNUOVc1YjgKLS0tIGszOW1qZk5qNWFnOTY1ZEtFN2Jz
            cis3ZS9MK2EvMGEwK29waW1tN3RHZ28K/p4O09stpizZ9bChSzzPCx1EiYrsoIdv
            cwNWFKy3iYYl4WUjeiZG5Q0KOqGaajRSisZkbxUsYKzovCtFU+WI0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-13T19:50:26Z"
    mac: ENC[AES256_GCM,data:k4F52HK7F9g6pPLzVQ1bD2r+mB9voL11KQniHG5MdLbYaI1Vqb/kBPcBf2i4aOo7k9oFNfQa8RivLFj1htxmAIjF40o8ZgDGmA02Qv7szxGCQVfV6ZyK9Gw5RcIVWCemILPxPKk63PCodZr/b3lxN6uh14XXHE4sbMboOPjyN3Q=,iv:18OlaRp9jK+IuhnbyaX+S8RWChX3LEEjEnKjAFutKbs=,tag:Pq1TvXgPO3zF2MicgP8NmQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
