---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deluge
  namespace: deluge
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      deluge:
        containers:
          app:
            image:
              repository: linuxserver/deluge
              tag: latest
            env:
              TZ: "America/Chicago"
              PUID: "1002"
              PGID: "1002"
              UMASK: "000"
              DELUGE_LOGLEVEL: "debug"
            resources:
              requests:
                cpu: 500m
                memory: 2048Mi
              limits:
                memory: 16Gi
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "weather-sunset"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
        - host: "deluge.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "deluge.${SECRET_DOMAIN}"
          secretName: deluge-tls
    persistence:
      config:
        enabled: true
        storageClass: freenas-iscsi-csi
        accessMode: ReadWriteOnce
        size: 10Gi
        mountPath: /config
        retain: true
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.86.5
            path: /srv/scratch/downloads
        mountPath: /downloads
      tank:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.86.2
            path: /mnt/tank/media/
        mountPath: /tank/media
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      torrent:
        enabled: true
        nameOverride: torrent
        type: LoadBalancer
        ports:
          primary:
            enabled: true
            #port: 33165
            port: 6881
            protocol: TCP
            #targetPort: 33165
            targetPort: 6881
          incoming-udp:
            enabled: true
            #port: 33165
            port: 6881
            protocol: UDP
            #targetPort: 33165
            targetPort: 6881
          daemon:
            enabled: true
            port: 58846
            protocol: TCP
            targetPort: 58846
        loadBalancerIP: 192.168.86.43
      webui:
        enabled: true
        type: LoadBalancer
        ports:
          primary:
            enabled: true
            port: 8112
            protocol: TCP
            targetPort: 8112
