---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kapowarr
  namespace: kapowarr
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      sonarr:
        containers:
          app:
            image:
              repository: mrcas/kapowarr
              tag: latest
            env:
              TZ: "America/Chicago"
              PUID: "1000"
              PGID: "1000"
              UMASK: "000"
            resources:
              requests:
                cpu: 500m
                memory: 2048Mi
              limits:
                memory: 16Gi
    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "weather-sunset"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
        - host: "kapowarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "kapowarr.${SECRET_DOMAIN}"
          secretName: kapowarr-tls
    persistence:
      db:
        enabled: true
        existingClaim: kapowarr-db
        globalMounts:
          - path: /app/db
            subPath: db
      scratch:
        enabled: true
        type: nfs
        server: 192.168.86.5
        path: /srv/scratch
        globalMounts:
          - path: /data/scratch
      tank:
        enabled: true
        type: nfs
        server: 192.168.86.2
        path: /mnt/tank/media
        globalMounts:
          - path: /data/tank/media/comics
            subPath: comics
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      kapowarr:
        ports:
          primary:
            port: 5656
            protocol: TCP
            targetPort: 5656
