---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 1m
  chart:
    spec:
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      # repository: ghcr.io/k8s-at-home/plex
      repository: ghcr.io/onedr0p/plex
      # Pinned to 1.25.4 due to HDR tone mapping issue with Dolby Vision
      # tag: v1.25.4.5468-989df2310
      tag: rolling
    env:
      TZ: "America/Chicago"
      ADVERTISE_IP: "http://192.168.86.42:32400/"
      ALLOWED_NETWORKS: "10.0.0.0/8, 192.168.0.0/16"
    service:
      main:
        type: LoadBalancer
        port:
          port: 32400
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        storageClass: freenas-iscsi-csi
        accessMode: ReadWriteOnce
        size: 1000Gi
        mountPath: /config
        retain: true
      dri:
        enabled: true
        type: hostPath
        hostPath: /dev/dri
        hostPathType: Directory
        mountPath: /dev/dri
      tank:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.86.2
            path: /mnt/tank/media
        mountPath: /mnt/tank/media
    podSecurityContext:
      runAsUser: 1002
      runAsGroup: 1002
      fsGroup: 1002
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
      - 44
      - 109
    resources: {}
    # empty braces makes this an empty map
    #requests:
    #  cpu: 1
    #  memory: 1024Mi
    #limits:
    #  memory: 4096Mi
    securityContext:
      privileged: true
