---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 1m
  chart:
    spec:
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: lscr.io/linuxserver/plex
      tag: latest
    env:
      TZ: "America/Chicago"
      ADVERTISE_IP: "http://192.168.86.42:32400/"
      ALLOWED_NETWORKS: "10.0.0.0/8, 192.168.0.0/16"
    service:
      main:
        type: LoadBalancer
        port:
          port: 32400
        loadBalancerIP: 192.168.86.62
    ingress:
      main:
        enabled: false
    persistence:
      config:
        existingClaim: deluge-config
      #dri:
      #  enabled: true
      #  type: hostPath
      #  hostPath: /dev/dri
      #  hostPathType: Directory
      #  mountPath: /dev/dri
      tank:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.86.2
            path: /mnt/tank/media
        mountPath: /mnt/tank/media
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
      - 44
      - 109
    resources: {}
    #requests:
    #  cpu: 1
    #  memory: 1024Mi
    #limits:
    #  memory: 4096Mi
    #securityContext:
    #  privileged: true
