---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx-operator
  namespace: emqx-operator-system
spec:
  interval: 15m
  chart:
    spec:
      chart: emqx-operator
      # when updating this chart, emxq manifests must be commented out of
      # kustomization.yaml until the new version comes online or flux/kustomizations
      # will fail
      version: 2.2.27
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

