---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb-crds
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: crds
      version: 0.13.12
      sourceRef:
        kind: HelmRepository
        name: metallb-crds
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

