---
clusterName: home-talos # Configures the cluster's name.
endpoint: https://192.168.86.20:6443 # Endpoint is the canonical controlplane endpoint, which can be an IP address or a DNS hostname.
nodes:
  - hostname: chonker
    controlPlane: true
    ipAddress: 192.168.86.21
    installDisk: /dev/sda
  - hostname: smolboi
    controlPlane: true
    ipAddress: 192.168.86.22
    installDisk: /dev/sda
  - hostname: dapperhat
    controlPlane: true
    ipAddress: 192.168.86.23
    installDisk: /dev/sda
  - hostname: stargazer
    controlPlane: false
    ipAddress: 192.168.86.24
    installDisk: /dev/nvme0n1
    networkInterfaces:
      - interface: enp86s0
        dhcp: true
talosVersion: v1.10.5
allowSchedulingOnControlPlanes: true
cniConfig:
  name: none
patches:
  - |-
    cluster:
      proxy:
        disabled: true
controlPlane:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
          - siderolabs/intel-ucode
          - siderolabs/i915
      extraKernelArgs:
        - -init_on_alloc                      # Less security, faster puter
        - -init_on_free                       # Less security, faster puter
        - -selinux                            # Less security, faster puter
        - apparmor=0                          # Less security, faster puter
        - i915.enable_guc=3                   # Meteor Lake CPU / iGPU
        - init_on_alloc=0                     # Less security, faster puter
        - init_on_free=0                      # Less security, faster puter
        - mitigations=off                     # Less security, faster puter
        - security=none                       # Less security, faster puter
        - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU / iGPU
        - talos.auditd.disabled=1             # Less security, faster puter
      udev:
        rules:
          - # Intel GPU
            SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
  networkInterfaces:
    - interface: eno1
      dhcp: true
      vip:
        ip: 192.168.86.20
worker:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
          - siderolabs/intel-ucode
          - siderolabs/i915
      extraKernelArgs:
        - -init_on_alloc                      # Less security, faster puter
        - -init_on_free                       # Less security, faster puter
        - -selinux                            # Less security, faster puter
        - apparmor=0                          # Less security, faster puter
        - i915.enable_guc=3                   # Meteor Lake CPU / iGPU
        - init_on_alloc=0                     # Less security, faster puter
        - init_on_free=0                      # Less security, faster puter
        - mitigations=off                     # Less security, faster puter
        - security=none                       # Less security, faster puter
        - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU / iGPU
        - talos.auditd.disabled=1             # Less security, faster puter
      udev:
        rules:
          - # Intel GPU
            SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"

