---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pricebuddy-storage
  namespace: pricebuddy
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pricebuddy-database
  namespace: pricebuddy
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
