---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 1h
  chart:
    spec:
      chart: loki
      version: 6.41.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    loki:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:rss"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
        - "prometheus.${SECRET_DOMAIN}"
        paths:
          - /
        tls:
        - secretName: prometheus-tls
          hosts:
          - "prometheus.${SECRET_DOMAIN}"
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: freenas-iscsi-csi
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
    grafana:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:rss"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
        - "grafana.${SECRET_DOMAIN}"
        paths: /
        tls:
        - hosts:
          - "grafana.${SECRET_DOMAIN}"
          secretName: grafana-tls

