---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 1h
  chart:
    spec:
      chart: loki
      version: 6.49.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    deploymentMode: SimpleScalable
    loki:
      storage:
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
        type: s3
        s3:
          endpoint: "${MINIO_ENDPOINT}"
          region: us-east-1
          secretAccessKey: "${MINIO_SECRET_ACCESS_KEY}"
          accessKeyId": "${MINIO_ACCESS_KEY_ID}"
      schemaConfig:
        configs:
          - from: 2024-04-01
            object_store: s3
            store: tsdb
            schema: v13
            index:
              prefix: index_
              period: 24h
    gateway:
      enabled: false
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        external-dns/is-public: "true"
        hajimari.io/enable: "true"
        hajimari.io/icon: "mdi:notebook"
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
      hosts:
      - "loki.${SECRET_DOMAIN}"
      paths:
        distributor:
          - /api/prom/push
          - /loki/api/v1/push
        querier:
          - /api/prom/tail
          - /loki/api/v1/tail
        query-frontend:
          - /loki/api
        ruler:
          - /api/prom/rules
          - /loki/api/v1/rules
          - /prometheus/api/v1/rules
          - /prometheus/api/v1/alerts
      tls:
      - secretName: loki-tls
        hosts:
        - "loki.${SECRET_DOMAIN}"
    write:
      persistence:
        storageClass: freenas-iscsi-csi
    read:
      persistence:
        storageClass: freenas-iscsi-csi
    backend:
      persistence:
        storageClass: freenas-iscsi-csi
