---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 1m
  chart:
    spec:
      chart: jellyfin
      version: 2.7.0
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  values:
    image:
      repository: docker.io/jellyfin/jellyfin
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:jellyfish"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
        - host: "jellyfin.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "jellyfin.${SECRET_DOMAIN}"
          secretName: jellyfin-tls
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
      media:
        enabled: true
        type: nfs
        volumeSpec:
          nfs:
            server: 192.168.86.2
            path: /mnt/tank/media
        mountPath: /media

