---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      jellyfin:
        containers:
          app:
            image:
              repository: jellyfin/jellyfin
              tag: latest
            env:
              TZ: "America/Chicago"
              JELLYFIN_PublishedServerUrl: "https://jellyfin.${SECRET_DOMAIN}"
            resources:
              requests:
                cpu: 100m
              limits:
                gpu.intel.com/i915: 1
                memory: 16Gi
      #nodeSelector:
      #  gpu.intel.com/device-id.0300-7d51.present: "true"
    service:
      main:
        ports:
          primary:
            enabled: true
            protocol: HTTP
            port: 8096
          udp:
            enabled: true
            protocol: UDP
            port: 7359
    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:jellyfish"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
        - host: "jellyfin.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "jellyfin.${SECRET_DOMAIN}"
          secretName: jellyfin-tls
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
      tank:
        enabled: true
        type: nfs
        server: 192.168.86.2
        path: /mnt/tank/media
        globalMounts:
          - path: /mnt/tank/media
      tmpfs:
        type: emptyDir
        advancedMounts:
          jellyfin:
            app:
              - path: /cache
                subPath: cache
              - path: /transcode
                subPath: transcode
