apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-nfs-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: tank-media-pv
    volumeAttributes:
      server: 192.168.86.2
      share: /mnt/tank/media
