apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-nfs-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  nfs:
    server: "${NAS_IP}"
    path: /mnt/tank/media

