---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      home-assistant:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.7.1@sha256:5ed76e1de666b3522dcbef5d23e41283c925dd707dbcaa2fc0ecef981c0bc881
            env:
              TZ: America/New_York
              #HASS_HTTP_TRUSTED_PROXY_1: 192.168.42.0/24
              #HASS_HTTP_TRUSTED_PROXY_2: 10.42.0.0/16
            #envFrom:
            #  - secretRef:
            #      name: home-assistant-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "weather-sunset"
        hosts:
        - host: &host "ha.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host
          secretName: ha-tls
    persistence:
      config:
        existingClaim: home-assistant-config
        globalMounts:
          - path: /config
      tmpfs:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /config/logs
                subPath: logs
              - path: /config/tts
                subPath: tts
              - path: /tmp
                subPath: tmp
              - path: /config/.venv
                subPath: .venv
