---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fusion-data
  namespace: fusion
labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

