apiVersion: v1
kind: Secret
metadata:
    name: studylion-secret
    namespace: studylion
type: Opaque
stringData:
    #ENC[AES256_GCM,data:1lL2acvg9WWnM1PkQJYh0hwvGIukBEHLFhXEYVB0uB+RQmwxUKtsvC4uUDLbwgrnF5/DJN8T,iv:3NG9nhMH767vnbm7/ZAo8C1TqLaeZZz1kNnM7p4Gmt4=,tag:BEtkHcqqhcZ/5EHkT16cvA==,type:comment]
    LIONBOT__STUDYLION__TOKEN: ENC[AES256_GCM,data:q4o8SPb9QZJbY8l03C5hfsodwHFCLJl+uykS4EGbFwzyfWqtoa1L19PIZNwJgRa0GZ0FfTsW58hisrBqJZrGmKLR8SJLKiHY,iv:KKGBFvv9vwW+bsFqWxJZWjXMVF+T7NuH87yIyGfY17A=,tag:CqQA7gaXPirGBtZM9oU7BA==,type:str]
    #ENC[AES256_GCM,data:vSp2ODr+Eyoh+6IQ+nQZqyIbjXs3VL3RE5jvtv9JdwB8H5N1FVNN9eLAJcLECS1aaUPWQuwUPtXwj9neGaSz,iv:KOYr9OCWCLv4+jVBsJtxxq7zVw3zzMTsPDlwHLxpx4M=,tag:dPGtsGbKpnxn/HWNhD4DWw==,type:comment]
    LIONBOT__STUDYLION__ADMINS: ENC[AES256_GCM,data:ClZlILkrjBURC11cRSAJyiiA,iv:A4AVH15rvLEyPPNJfMencmuAWrhl4ck052GnmgzjThg=,tag:juiwHLw04Ev+7zJH0xRF3w==,type:str]
    LIONBOT__STUDYLION__ADMIN_GUILDS: ENC[AES256_GCM,data:9pJa3rFGsC9FlyxILhwEp/p0C0Owi3vDSOJif3mV81EN96r1KUkbwg==,iv:7nMigVF5mY/LKZX/kCW4u2ggdnZwCVu3m1WwON387RY=,tag:A3j7jk/wob+eiomIdoygjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3U0ZyZk9ud09md1l4cE5s
            SC9LdkNJQVg5bkxLSm9mOWVLOVExQXlsR0R3CjdFa044czRuaU5vOEw2WFNIK1h3
            ME5hR25DbWlUbG1MeDdLQk5xK2JjalUKLS0tIFc2c0UrVUZMdHY2YnJSeUVka1dT
            WnFEb3pGZXhrbk9aazJPaWVabUoxYXMKJMiW5PVJv00cpLhTzp9FmFJcfM/wI8+N
            TNmwVWBYJ7TLRkEsKRkSTaFiwsL747TEushvwR9AuaYr9SssUPYBGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vcv85qmhme0zc9ncdvgw9mq0cr2fjewts3ne2g8xnngvpktwapxq5x9reu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T22:20:47Z"
    mac: ENC[AES256_GCM,data:rvEwkbMe9VmOhl6GHtT0WRehsvSHp5rPd+xU00elDDVwvKyI3GM+6xYkqaZxP6LM7CzBXlIrRVtW6XlZbjyYo3b3rAGjAre9TrQWDhotzApk+z+hglSQECuOgrAzmxp9TxriwRYaUKSAKrmW4U6wSFIxisD500mjY/HzJ2R93ww=,iv:Js15bDXC1OgcBxKTVrgvFM6TYjMLEDQjWerVM9QRKXQ=,tag:CtJlhGO8fqVtCs9Aa59iCQ==,type:str]
    version: 3.13.3
