---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-pihole
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    interval: 5m
    logLevel: debug
    labelFilter: "external-dns-pihole=enable"
    provider: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        value: "${EXTERNAL_DNS_PIHOLE_PASSWORD}"
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: "http://${PIHOLE_SERVER}"
    args:
      - "--pihole-api-version=6"
    policy: sync
    regisrty: noop
    sources:
      - ingress
    txtPrefix: "k8s."
    txtOwnerId: "default"
    domainFilters:
      - "${SECRET_DOMAIN}"
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi
    serviceMonitor:
      enabled: true
