# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:wPPdSS5IgP+6Rjjh54tQZT/+S2J3RQal,iv:6zG+h9w3I50rz9X+YSsuH+AHa2Lmfs387/fpbOFwHjc=,tag:x7sinDPGnJbOEDpQhWJBDA==,type:str]
    api-key: ENC[AES256_GCM,data:mAKU2pByTpA8INnRaWuSOSCu0bJ5larwm4I/MQGgzCzq5EFZtQ==,iv:dWp5WjfZsih+wBOeCrQE3KW9WrADW+nKLsaJfrRE+Rw=,tag:1NtqXAOsTrhDjfGZXJXBpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vcv85qmhme0zc9ncdvgw9mq0cr2fjewts3ne2g8xnngvpktwapxq5x9reu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWL2ZTODloRGVNaTFaakVw
            WG9Ya0tHM3VNa0NHMW9OS1BQQmIwNk1XeWs4CldPWk9WTlNJTUptOXkzbjRLZTBV
            bDZmVzhMOTRNaGU5aC81L3laY0FmbUEKLS0tIC9VRlErN1BDWC9hMk1wU25yR0E0
            a3Q1cnluV3dZNEpWUVROMC9wTWJpRGcK6ymGRtlrftIuZlRQ4F4Xuav3DIvdjC80
            bPqt8P4aOQT20mtXKGLqv8p6EoZjDdpcElvXhv7nUBBtgQAtfom9rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-04T21:16:44Z"
    mac: ENC[AES256_GCM,data:SDOEtQOnJiMmvJO3gH4Mv7t3y2aa6DMNpR3+TfgZr43SDkwqs35vVS4GVsPrf3Z6VCOky21I163FyB8RwrsLKcUoL1FbY4vJ1CEWCNo8kFAGpBeMNOmJaTKCGWdNSabzBAYizXcHRjWqHRtoMfWldBA1XVicGzhaA5kTQeoI+Ho=,iv:U38SWUKqJOmPn0885v9+MARVSbDt+eWMUVRL40DV7Mw=,tag:yobZ6GQB6C4qDlaCnygCKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
