---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 15m
  chart:
    spec:
      chart: *app
      version: "0.17.1"
      sourceRef:
        kind: HelmRepository
        name: nfd
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  values:
    prometheus:
      enable: true
    worker:
      config:
        sources:
          usb:
            deviceClassWhitelist:
              - "0e"
              - "ef"
              - "fe"
              - "ff"
              - "02"
              - "0a"
